### ISSUE TITLE
Unzip the sharp images

### ISSUE THREAD

**Issue by dongliangcao** [rimchang/RSBlur#1]
Dear Authors,

Thanks a lot for making the new realistic dataset for image deblurring publicly available. I just encounter a problem when I try to unzip the sharp images shared in the google drive. Could you provide some hints to help me to unzip all sharp images. 

Best regards
Dongliang

**Comment by rimchang** [comment]
We provide multi-part zip files due to the large size of the dataset.
First, download all zip files (RSBlur_sharps.z01~z13 and RSBlur_sharps.zip).
Then, combine all zip files into one file using the below command.

```
zip -s- RSBlur_sharps.zip -O RSBlur_sharps_combined.zip
```

Finally, you can unzip the combined zip file.

```
unzip RSBlur_sharps_combined.zip
```
Best regards
