### ISSUE TITLE
Frame Interpolation method.

### ISSUE THREAD

**Issue by RushiPardeshi** [rimchang/RSBlur#4]
As mentioned in the paper, ABME is used for frame interpolation in which 9 sharp images are used to increase them to 65. However, ABME takes two sharp images as input to create the interpolated frame. 
I want to imitate your blur generation pipeline on  a new dataset. Hence may I know the exact step you followed in your paper.

Best Regards

**Comment by rimchang** [comment]
Thanks for your interest in our paper.

We use ABME in a recursive way for multi-frame interpolation.

We apply ABME three times to 9 sharp images and get 65 interpolated images.

Please refer to the multi-frame interpolation code of ABME.

https://github.com/JunHeum/ABME/blob/70e5e04070ce572c5260ce45baa7388ec8b26ddd/test.py#L141

Best Regards.
