### ISSUE TITLE
How to generate a saturation mask Image for sharp Image

### ISSUE THREAD

**Issue by ClimaxW** [rimchang/RSBlur#6]
Hi,Thanks for your work.It's cool!But I encountered some issues while trying to reproduce it.

There is already an issue about how to generate blurred data, but in that issue, the author started with Saturation synthesis and skipped the step of generating a saturation mask image. In order to use it on other datasets, can you let me know how to generate the saturation mask image for a clear image. Thank you for any assistance.

**Comment by rimchang** [comment]
Thanks for your interest in our paper.

Here are some example codes.

For the averaging based method, if you have a sharp images (linear-RGB) list as:

```python
imgs_list = [img1, img2, img3, ..., img9]
```

We can model a blurred image as:
```python
B = np.mean(imgs_list, axis=0)
```

Then, we compute the saturation mask (M_sat) as:

```python
# saturated pixels of images
sat_pixels_list = [(img==1).astype('float32') for img in imgs_list] 
M_sat = np.mean(sat_pixels_list, axis=0)
```

For the kernel based method, if you have a blur kernel K and a sharp image I (linear-RGB).

Then, we can model a blurred image as:

```python
B = np.convolve(I, K, mode='full')
```

We compute the saturation mask (M_sat) as:

```python
# saturated pixels of an image
sat_pixels = (I==1).astype('float32') 
M_sat = np.convolve(sat_pixels, K, mode='full')
```

Thank you.
